project:
  type: website
  output-dir: _site

execute:
  freeze: auto

format:
  html:
    toc: true
    toc-location: right
    theme:
      light: flatly
      dark: darkly

website:
  title: "cache!"
  
  # Top navigation bar
  navbar:
    left:
      - href: index.md
        text: Home
      - href: https://darkcheftar.github.io/
        text: About

  # Side navigation (Great for many notes)
  sidebar:
    style: "docked"
    search: true            # This adds a search bar automatically!
    collapse-level: 2  # Shows the first two levels, collapses the rest
    contents:
      - section: "Deep Learning"
        contents:
          - section: Neural ODEs
            contents: src/machine_learning/neural_ode/*
          - section: "Graph Neural Networks"
            contents: src/machine_learning/gnns/*
      - section: "Uncertainty Quantifcation"
        contents: src/uq/*
      - notes.md
